#*Numpy has two flavours one is vector= 1D arrays and another matrix=2D arrays

In [1]:
list=[1,2,3]

In [2]:
import numpy as np
np.array(list)

array([1, 2, 3])

In [4]:
arr=np.array(list)
arr

array([1, 2, 3])

# List of a list and converting into array

In [6]:
list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list) # 2D arrays

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)#arange() is the inbuit function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2) # 2 is the step size

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)# 1D array, vector form, 1 set of [] is 1 D array

array([0., 0., 0.])

In [17]:
np.zeros((5,5))# 2D arrays, matrix form, 2 set of [], i.e., [[]] is 2D array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3)) # 2 rows and 3 column

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#linspace is a little different than arange.
#1[]= 1D array
#2[]=[[]]=2D array

In [20]:
np.linspace(0,5,10) # o to 5 , there are 10 equally spaced numbers

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
#Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#1D random number
np.random.rand(5)

array([0.27336653, 0.97891372, 0.38758662, 0.77696793, 0.07947043])

In [23]:
#2D random number
np.random.rand(5,5)

array([[0.48084295, 0.0800853 , 0.03313336, 0.10596146, 0.55883948],
       [0.12253014, 0.79936833, 0.72192719, 0.65567758, 0.49458324],
       [0.13984798, 0.83222852, 0.04848582, 0.66355962, 0.18169773],
       [0.85500404, 0.6088282 , 0.34464596, 0.27189137, 0.42793756],
       [0.35065454, 0.17077037, 0.5593123 , 0.50306193, 0.03229021]])

In [24]:
#random distribution for normal(gaussian) distribution
np.random.randn(4)

array([-1.69493586,  1.32649774, -0.28878837,  1.20557266])

In [25]:
np.random.randn(4,4)

array([[ 0.52688401,  0.27566353, -1.30634679, -0.85450726],
       [ 0.14511748, -0.37743978,  2.56575883,  0.77764514],
       [-0.64176701,  0.26395168,  0.53859889, -0.06280372],
       [-0.29911062,  0.1155004 , -1.4582336 , -0.03963449]])

In [26]:
# to get the random integer
np.random.randint(0,100,10)

array([34, 32, 58, 50, 84, 14, 83, 97, 22, 89])

In [29]:
# Reshape the array
array=np.arange(25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
#max and min value of an array
np.random.randint(0,100,10)

array([64, 58, 52, 80, 96, 77, 49, 46, 13, 87])

In [36]:
arr.max()

3

In [37]:
arr.min()

1

In [41]:
arr=np.random.randint(0,10,5)
arr

array([3, 8, 7, 1, 8])

In [42]:
arr.max()

8

In [43]:
arr.min()

1

In [44]:
arr.argmax()

1

In [45]:
arr.argmin()

3

In [46]:
arr.shape

(5,)

In [48]:
#data type here is 64 bit integer
arr.dtype

dtype('int64')

In [49]:
# call at the beginning
from numpy.random import randint
randint(2,10)

4

# Numpy indexing and selection

In [50]:
import numpy as np

In [52]:
arr=np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8]

8

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [57]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [58]:
arr[5:8]

array([5, 6, 7])

In [68]:
# Broadcasting a value
arr[0:5]=100

In [69]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [70]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [71]:
slice_of_arr=arr[0:6]

In [72]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [73]:
arr_copy=arr.copy()

In [74]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [75]:
arr_copy[:]=100

In [77]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [78]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# creating a 2D array

In [79]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [80]:
arr_2d[0][0] #first row and first column of the given matrix=2D array

5

In [81]:
arr_2d[0]#first row of a matrix

array([ 5, 10, 15])

In [82]:
arr_2d[2][1]

40

In [83]:
arr_2d[2,1]

40

In [84]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [85]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [86]:
#array conditional

In [87]:
arr=np.arange(1,11)

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
bool_arr=arr>5

In [90]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [91]:
#This means arr>5 means, printout False for arr<5 and True for arr>5

In [92]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [93]:
arr_2d=np.arange(50).reshape(5,10)

In [94]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [95]:
arr_2d[1:3,3:5]# row 1 and 2,column 3 and 4

array([[13, 14],
       [23, 24]])

# Numpy operation

In [96]:
import numpy as np

In [97]:
arr=np.arange(0,11)

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [102]:
arr*arr*arr

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [103]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [104]:
1 /arr

/Users/bhawindhital/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [105]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [106]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [107]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [108]:
np.max(arr)

10

In [109]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [110]:
np.log(arr)

/Users/bhawindhital/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Numpy Exercise

In [111]:
import numpy as np

In [112]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [207]:
sum=np.zeros(10)+5
sum

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [120]:
# create an integer from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [121]:
np.arange(10,51,2) # even integer between 10 and 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [122]:
# create a 3by3 matrix the vlues ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
#create 3 by 3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
# use numpy to generate the random number between 0 and 1
arr=np.random.rand(1)
arr


array([0.73541157])

In [141]:
#use numpy to generate an array of 25 random numbers sampled from the standard normal distributions

In [142]:
arr1=np.random.randn(25)
arr1

array([-1.15944384,  0.33297552, -1.27126754,  0.6935983 ,  1.23745285,
        0.09521117, -0.49699839, -0.18772685,  0.17670949,  0.34714993,
       -0.42980211,  0.32265481, -0.7868009 ,  0.90993709,  0.2550126 ,
        0.44407094,  1.11071576,  0.89474235, -0.8204554 ,  0.34302362,
       -0.19117781, -0.39601458, -0.83325686,  0.16032309,  1.27652643])

In [146]:
arr_2d=np.arange(0.01,1.01,0.01).reshape(10,10)
arr_2d

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [208]:
arr_2d=np.arange(1,101).reshape(10,10)/100
arr_2d

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [147]:
# create an array of 20 linearly spaced point between 0 and 1
arr2=np.linspace(0,1,20)
arr2

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and selection

In [169]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [178]:
mat[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [210]:
mat[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [213]:
mat[3,4]

20

In [214]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [215]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [216]:
mat[4]

array([21, 22, 23, 24, 25])

In [217]:
mat[-1:,]

array([[21, 22, 23, 24, 25]])

In [218]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [220]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [192]:
np.sum(mat) # sum of all elements in the matrix

325

In [221]:
mat.sum()

325

In [223]:
mat.std()

7.211102550927978

In [193]:
np.std(mat)# standard deviation of all elements in a matrix

7.211102550927978

In [201]:
mat.sum(axis=0)# sum of each columns of the given matrix

array([55, 60, 65, 70, 75])

In [202]:
mat.sum(axis=1)# sum of each rows of the given matrix

array([ 15,  40,  65,  90, 115])