# Numpy tutorials started on Dec 24,2019! Happy Hollidays

In [3]:
import numpy as np
num = [[1,2,3],[4,5,6],[7,8,9]]
num1=np.array(num) # This gives array form 
print(num1)
print(num1.ndim) # dimension of the given array.
print(num1.shape) # shape 3 by 3


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


# create numpy arrays using functions

# zeros , ones,eyes, diag, randint, rand, randn

In [4]:
import numpy as np
array = np.zeros(5)
print(array) # will give five element and all of them will be zeros.

[0. 0. 0. 0. 0.]


In [5]:
# you can make a tuple using aray
arr1=np.zeros((2,3))
print(arr1)
print(arr1.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [8]:
arr2=np.ones(4)
print(arr2)
print(arr2.ndim)

[1. 1. 1. 1.]
1


In [11]:
import numpy as np
arr3=np.eye(3)
print(arr3) #eye gives identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
arr0=np.diag([1,2,3,4])
print(arr0) #diagonal square matrix

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [13]:
import numpy as np
arrr1=np.eye(3)
print(np.diag(arrr1))# find out the diagonal of the matrix

[1. 1. 1.]


# Generate the random array

In [16]:
rand_arr=np.random.randint(4,10,5) # It means 5 random integer between 4 and 10
print(rand_arr)

[9 4 6 8 7]


In [18]:
ran=np.random.rand(5)
print(ran) #printout one dimensional array

[0.76246184 0.90051931 0.3225446  0.80563513 0.38498554]


In [20]:
#two dimensional array
ran1=np.random.rand(2,2) # two dimensional array, 2 by 2 matrix
print(ran1)

[[0.82797225 0.04355406]
 [0.58989248 0.22747986]]


In [22]:
ran3=np.random.randn(4)
print(ran3) #zero will be the center and other numbers around.

[ 0.00314143  0.31121914 -1.37665561  0.39846236]


In [24]:
#mean of the above random function
ran4=np.random.randn(4)
print(np.mean(ran4))

0.35928931584351603


# Reshaping the data

In [34]:
import numpy as np
a1=np.random.randint(1,100,20) # 20 integer between 1 and 100
print(a1)
print(a1.ndim) #dimension, 1 dim array
print(a1.shape)
#Reshape from 1 D to 2 D and so on
print(a1.reshape(4,5)) # Reshape 20 values in 4 by 5 matrix
# 3 D array
print(a1.reshape(2,2,5))
print(a1.ndim)

[20  7 57 80 63 31  6  4 19 40 58 73 18 17 35 78 97 54 60 18]
1
(20,)
[[20  7 57 80 63]
 [31  6  4 19 40]
 [58 73 18 17 35]
 [78 97 54 60 18]]
[[[20  7 57 80 63]
  [31  6  4 19 40]]

 [[58 73 18 17 35]
  [78 97 54 60 18]]]
1


In [42]:
# Arrange the data
import numpy as np
arr=np.arange(1,21)
print(arr)
print(arr.reshape(5,-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


# Seed function

In [47]:
import numpy as np
np.random.seed(0)
arr=np.random.randint(1,100,10)
print(arr)
print(arr.size)

[45 48 65 68 68 10 84 22 37 88]
10


# Indexing and Slicing

In [49]:
import numpy as np
arra=np.array([5,10,15,20,25])
print(arra)
print(arra[2])
print(arra[-3])

[ 5 10 15 20 25]
15
15


In [54]:
print(arra[0:])
print(arra[0:3])
print(arra[:-1])
print(arra[0:-1:2])#print the slice of 
print(arra[::-1]) #reverse the array

[ 5 10 15 20 25]
[ 5 10 15]
[ 5 10 15 20]
[ 5 15]
[25 20 15 10  5]


# 2 D matrix indexing and slicing

In [56]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2 D array
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
#indexing using the double bracket notation
print(matrix[0][1])
print(matrix[1][2])

2
6


In [63]:
#indexing using a single brackett 
print(matrix[0,1])
print(matrix[:1])
print(matrix[:2,:2])
print(matrix[:1,:1:1])

2
[[1 2 3]]
[[1 2]
 [4 5]]
[[1]]


In [64]:
#you can extract the element
print(matrix[1:3,1:3])

[[5 6]
 [8 9]]


In [65]:
#To make a big array
np.random.seed(123)
matrix1=np.random.randint(1,100,25).reshape(5,5)
print(matrix1)

[[67 93 99 18 84]
 [58 87 98 97 48]
 [74 33 47 97 26]
 [84 79 37 97 81]
 [69 50 56 68  3]]


In [68]:
# to extract some element
print(matrix1[1:4,1:4])

[[87 98 97]
 [33 47 97]
 [79 37 97]]


# Copy 

In [69]:
import numpy as np
arr=np.array([5,10,15,20,25,30])
print(arr)
slice1=arr[2:5].copy()
print(slice1)
slice1[:]=0
print(slice1)
print(arr) # slice1 is the copy of the original that means they have the different memory location.

[ 5 10 15 20 25 30]
[15 20 25]
[0 0 0]
[ 5 10 15 20 25 30]


In [70]:
# conditional selection
import numpy as np
arr=np.arange(1,11)
print(arr)
print(arr>5)
mask=arr>5
print(arr[mask])
print(arr[arr<4])
print(arr[arr%2==0])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[1 2 3]
[ 2  4  6  8 10]


In [72]:
# numerical operation with array
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr*2)
print(arr**2)
print(arr+5)

[1 2 3 4]
[2 4 6 8]
[ 1  4  9 16]
[6 7 8 9]


# Numerical operations in more than two arrays

In [75]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1+arr2)
arr3=arr1+arr2
print(arr3)
arr4=arr1*arr2
print(arr4)
print(arr1*arr1)

[ 6  8 10 12]
[ 6  8 10 12]
[ 5 12 21 32]
[ 1  4  9 16]


In [77]:
np.random.seed(123)
matrix1=np.random.randint(1,12,9).reshape(3,3)
matrix2=np.random.randint(1,15,9).reshape(3,3)
print(matrix1)
print(matrix2)
print(matrix1*matrix2)
print(matrix1.dot(matrix2))


[[ 3  3  7]
 [ 2  4 11]
 [10  7  2]]
[[ 1  2 10]
 [ 1  1 10]
 [ 4 14  5]]
[[  3   6  70]
 [  2   4 110]
 [ 40  98  10]]
[[ 34 107  95]
 [ 50 162 115]
 [ 25  55 180]]


# Useful numpy functions

In [78]:
arr=np.array([5,2,50,40,39,20])
print(arr)
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.sqrt(arr))

[ 5  2 50 40 39 20]
2
50
1
[2.23606798 1.41421356 7.07106781 6.32455532 6.244998   4.47213595]


In [79]:
print(np.exp(arr))

[1.48413159e+02 7.38905610e+00 5.18470553e+21 2.35385267e+17
 8.65934004e+16 4.85165195e+08]


In [80]:
print(np.sin(arr))

[-0.95892427  0.90929743 -0.26237485  0.74511316  0.96379539  0.91294525]


In [81]:
print(np.linspace(1,15,20)) #will give 20 numbers between 1 and 15 and all of them are equally spaced.

[ 1.          1.73684211  2.47368421  3.21052632  3.94736842  4.68421053
  5.42105263  6.15789474  6.89473684  7.63157895  8.36842105  9.10526316
  9.84210526 10.57894737 11.31578947 12.05263158 12.78947368 13.52631579
 14.26315789 15.        ]


# Boolean array

In [86]:
arry=np.array([1,2,3,0],dtype='bool') # boolean has zero as a false statement
print(arry)
arry3=np.array([10,0,0,1,0,2,3,0],dtype='bool')
print(arry3)

[ True  True  True False]
[ True False False  True False  True  True False]


# Numpy axis

In [87]:
import numpy as np
np.random.seed(123)
matrix=np.random.randint(1,11,9).reshape(3,3)
print(matrix)
print(np.sum(matrix))
print(matrix.sum())

[[ 3  3  7]
 [ 2  4 10]
 [ 7  2  1]]
39
39


In [88]:
print(np.min(matrix))

1


In [89]:
# need to memorize rows = 1, columns = 0
print(np.min(matrix,axis=1)) # this will select smallest number from each row and make a new row
print(np.min(matrix,axis=0))

[3 2 1]
[2 2 1]


In [90]:
# to sum row wise
print(np.sum(matrix,axis=1))

[13 16 10]


# Cumulative sum

In [92]:
print(np.cumsum(matrix,axis=0)) #cumulative sum, first row adds to second row and so on

[[ 3  3  7]
 [ 5  7 17]
 [12  9 18]]


In [94]:
# can do product wise as well
print(np.prod(matrix,axis=1))

[63 80 14]


# Shuffle and Unique(Shuffle means changing the position of the items)

In [96]:
import numpy as np
np.random.seed(123)
arr=np.random.randint(1,15,15)
print(arr)

[14  3 13  3  7  2  4 11 12 10  7  2  1  2 10]


In [98]:
np.random.shuffle(arr)
print(arr)

[14 10  3 11  7  2  2  3 13 12  2  7  4 10  1]


In [99]:
np.unique(arr) #shows only one time

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [100]:
arr1=np.unique(arr,return_index=True,return_counts=True) # the first line is the unique array,second
print(arr1)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]), array([14,  5,  2, 12,  4,  1,  3,  9,  8,  0]), array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1]))


# Horizontal stacking

In [101]:
np.random.seed(123)
matrix1=np.random.randint(1,20,9).reshape(3,3)
matrix2=np.random.randint(20,40,9).reshape(3,3)
print(matrix1)
print(matrix2)

[[14  3  3]
 [ 7 18 11]
 [ 2  1 18]]
[[35 29 20]
 [34 20 35]
 [39 34 24]]


In [102]:
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [103]:
np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

# One dimensional array

In [104]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [105]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [109]:
arr1=np.arange(20,41)
print(arr1)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [110]:
arr5=np.ones(10)*5
print(arr5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Create 1 D array and its conversion

In [112]:
arr3=np.random.randint(1,50,24)
print(arr3)

[ 4 43  6  1 12 35 11 23 14 19 37 16 44 28 45 31  7 46 27 17  7 15 40 12]


In [113]:
# converting into 3 D array
arr4=np.random.randint(1,50,24).reshape(3,4,2)
print(arr4)

[[[ 8  2]
  [44 38]
  [26 21]
  [13 19]]

 [[18  2]
  [45 42]
  [49 28]
  [23  4]]

 [[ 4 12]
  [22 26]
  [40 42]
  [35  4]]]


In [115]:
arr=np.random.rand(4,4)
print(arr)

[[0.9097694  0.21837601 0.36310407 0.85497282]
 [0.7113918  0.39294441 0.23130148 0.38017471]
 [0.5491621  0.55671906 0.00413464 0.63802252]
 [0.05764801 0.04302691 0.87505113 0.2925876 ]]


# Create an array with 20 random integer and replcae every number by -1

In [116]:
np.random.seed(123)
arry1=np.random.randint(1,50,20)
print(arry1)
arry1[arry1%2==0]=-1
print(arry1)

[46  3 29 35 39 18 20 43 23 34 33 48 10 33 47 33 48 26 20 15]
[-1  3 29 35 39 -1 -1 43 23 -1 33 -1 -1 33 47 33 -1 -1 -1 15]


# Concatenate to 1 D array

In [123]:
import numpy as np
arry2=np.array([1,2,3])
arry3=np.array([4,5,6])
print(np.vstack((arry2,arry3)))

[[1 2 3]
 [4 5 6]]


In [122]:
%timeit 2+3

6.73 ns ± 0.0921 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [124]:
%timeit [i**2 for i in range(1,4)]

880 ns ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [128]:
#calculate the time of whole block.
%timeit
l=[]
for i in range(1,4):
    l.append(i**2)


In [129]:
import numpy as np
%timeit np.arange(1,4)**2

1.02 µs ± 20.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Before going to Pandas download any file from Kaggle.com #data.world

# Pandas

In [130]:
import pandas as pd
pd.__version__ # pandas version

'0.25.1'

In [131]:
l=[1,2,-3,6.5,'data values']
print(l)

[1, 2, -3, 6.5, 'data values']


In [132]:
# create a series with the help of above list
s1=pd.Series(l)
print(s1)

0              1
1              2
2             -3
3            6.5
4    data values
dtype: object


In [133]:
# type of the series
print(type(s1))

<class 'pandas.core.series.Series'>


In [134]:
# creating a series by short method
s2=pd.Series([1,2,3,4])
print(s2)

0    1
1    2
2    3
3    4
dtype: int64


In [135]:
# Create an empty series
s3=pd.Series([])
print(s3)

Series([], dtype: float64)


In [136]:
s4=pd.Series([1,2,3,4], index=['a','b','c','d'])
print(s4)

a    1
b    2
c    3
d    4
dtype: int64


In [137]:
# you can change the data type to float
s5=pd.Series([1,2,3,4],index=[10,20,30,40],dtype=float)
print(s5)

10    1.0
20    2.0
30    3.0
40    4.0
dtype: float64


In [139]:
# you can also provide the name to the data value column
s6=pd.Series([1,2,3,4],index=[10,20,30,40],dtype=float,name='data_values')
print(s6)

10    1.0
20    2.0
30    3.0
40    4.0
Name: data_values, dtype: float64


In [140]:
# you can create a series by using the scalar value
scalar=pd.Series(0.5)
print(scalar)

0    0.5
dtype: float64


In [142]:
# for more value and indexing
scalar1=pd.Series(0.5,index=[1,2,3,4])
print(scalar1)

1    0.5
2    0.5
3    0.5
4    0.5
dtype: float64


In [143]:
#you can create series by using a dictionery
dict_s=pd.Series({'a':1,'b':2,'x':5})
print(dict_s)

a    1
b    2
x    5
dtype: int64


In [144]:
# creating a series and operation
s6=pd.Series([1,2,3,4,5])
print(s6)
print(s6[0])
print(s6[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
1
4


In [146]:
# slice of a series
s6=pd.Series([1,2,3,4,5])
s7=s6[0:4]
print(s7)

0    1
1    2
2    3
3    4
dtype: int64


In [149]:
# min amd max values
s6=pd.Series([-5,1,2,3,4,5,10])
print(max(s6))
print(min(s6))

10
-5


In [150]:
# value greater than in the lsit
s8=s6[s6>3]
print(s8)

4     4
5     5
6    10
dtype: int64


In [151]:
s9=pd.Series([-5,1,2,3,4,5,12])
s10=pd.Series([-50,10,20,30,40,50,100])
print(s10)
print(s9)

0    -50
1     10
2     20
3     30
4     40
5     50
6    100
dtype: int64
0    -5
1     1
2     2
3     3
4     4
5     5
6    12
dtype: int64


In [152]:
s11=s9+s10
print(s11)

0    -55
1     11
2     22
3     33
4     44
5     55
6    112
dtype: int64


# Panda data frame

In [153]:
# pandas data frame is 2d size mutable, potentially
# how to create python pandas data frame?

In [154]:
import pandas as pd
empt=pd.DataFrame() # empty data frame
print(empt)

Empty DataFrame
Columns: []
Index: []


In [155]:
# create a dataframe from a list
list=['a','b','c','d']
print(list)

['a', 'b', 'c', 'd']


In [156]:
# make a data frame
df1=pd.DataFrame(list)
print(df1)

   0
0  a
1  b
2  c
3  d


In [157]:
# note 0 at the right top is the label
df1

0
0  a
1  b
2  c
3  d

In [158]:
# in the above, there is one index and one column
ls=[[1,2,3],[3,4,5],[6,7,8]]
print(ls)

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]


In [159]:
df2=pd.DataFrame(ls)
print(df2)

   0  1  2
0  1  2  3
1  3  4  5
2  6  7  8


In [160]:
dict1={'id':[1,2,3,4],'sh':[2,4,5,6],'bh':[2,3,4,6]}
df4=pd.DataFrame(dict1)
print(df4)

   id  sh  bh
0   1   2   2
1   2   4   3
2   3   5   4
3   4   6   6


# How to read csv files in pandas?

In [162]:
import pandas as pd
import numpy as np
csv=pd.read_csv('season-1819_csv.csv')
print(csv)

    Div        Date      HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  \
0    E0  10/08/2018    Man United       Leicester     2     1   H     1     0   
1    E0  11/08/2018   Bournemouth         Cardiff     2     0   H     1     0   
2    E0  11/08/2018        Fulham  Crystal Palace     0     2   A     0     1   
3    E0  11/08/2018  Huddersfield         Chelsea     0     3   A     0     2   
4    E0  11/08/2018     Newcastle       Tottenham     1     2   A     1     2   
..   ..         ...           ...             ...   ...   ...  ..   ...   ...   
375  E0  12/05/2019     Liverpool          Wolves     2     0   H     1     0   
376  E0  12/05/2019    Man United         Cardiff     0     2   A     0     1   
377  E0  12/05/2019   Southampton    Huddersfield     1     1   D     1     0   
378  E0  12/05/2019     Tottenham         Everton     2     2   D     1     0   
379  E0  12/05/2019       Watford        West Ham     1     4   A     0     2   

    HTR  ... BbAv<2.5  BbAH

# How to write csv files in pandas
# Data processing, Data cleaning

In [163]:
import pandas as pd
df=pd.read_csv('season-1819_csv.csv')
print(df)

    Div        Date      HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  \
0    E0  10/08/2018    Man United       Leicester     2     1   H     1     0   
1    E0  11/08/2018   Bournemouth         Cardiff     2     0   H     1     0   
2    E0  11/08/2018        Fulham  Crystal Palace     0     2   A     0     1   
3    E0  11/08/2018  Huddersfield         Chelsea     0     3   A     0     2   
4    E0  11/08/2018     Newcastle       Tottenham     1     2   A     1     2   
..   ..         ...           ...             ...   ...   ...  ..   ...   ...   
375  E0  12/05/2019     Liverpool          Wolves     2     0   H     1     0   
376  E0  12/05/2019    Man United         Cardiff     0     2   A     0     1   
377  E0  12/05/2019   Southampton    Huddersfield     1     1   D     1     0   
378  E0  12/05/2019     Tottenham         Everton     2     2   D     1     0   
379  E0  12/05/2019       Watford        West Ham     1     4   A     0     2   

    HTR  ... BbAv<2.5  BbAH

In [164]:
# what is the type of the file?
type(df)

pandas.core.frame.DataFrame

In [166]:
# to see the column names
df.columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA',
       'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [167]:
df=pd.read_csv('season-1819_csv.csv',nrows=4)
df

Div        Date      HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  \
0  E0  10/08/2018    Man United       Leicester     2     1   H     1     0   
1  E0  11/08/2018   Bournemouth         Cardiff     2     0   H     1     0   
2  E0  11/08/2018        Fulham  Crystal Palace     0     2   A     0     1   
3  E0  11/08/2018  Huddersfield         Chelsea     0     3   A     0     2   

  HTR  ... BbAv<2.5  BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  PSCH  \
0   H  ...     1.79    17  -0.75     1.75     1.70     2.29     2.21  1.55   
1   H  ...     1.83    20  -0.75     2.20     2.13     1.80     1.75  1.88   
2   A  ...     1.87    22  -0.25     2.18     2.11     1.81     1.77  2.62   
3   A  ...     1.84    23   1.00     1.84     1.80     2.13     2.06  7.24   

   PSCD  PSCA  
0  4.07  7.69  
1  3.61  4.70  
2  3.38  2.90  
3  3.95  1.58  

[4 rows x 62 columns]

In [168]:
# to read some particular column
df=pd.read_csv('season-1819_csv.csv',usecols=[0])
print(df)

    Div
0    E0
1    E0
2    E0
3    E0
4    E0
..   ..
375  E0
376  E0
377  E0
378  E0
379  E0

[380 rows x 1 columns]


In [169]:
# to read more column
df=pd.read_csv('season-1819_csv.csv',usecols=[0,3])
print(df)# print only those columns for which the index is provided

    Div        AwayTeam
0    E0       Leicester
1    E0         Cardiff
2    E0  Crystal Palace
3    E0         Chelsea
4    E0       Tottenham
..   ..             ...
375  E0          Wolves
376  E0         Cardiff
377  E0    Huddersfield
378  E0         Everton
379  E0        West Ham

[380 rows x 2 columns]


In [170]:
# To skips some rows
df=pd.read_csv('season-1819_csv.csv',skiprows=[0,1,2])
print(df)

     E0  11/08/2018        Fulham Crystal Palace  0  2  A  0.1  1 A.1  ...  \
0    E0  11/08/2018  Huddersfield        Chelsea  0  3  A    0  2   A  ...   
1    E0  11/08/2018     Newcastle      Tottenham  1  2  A    1  2   A  ...   
2    E0  11/08/2018       Watford       Brighton  2  0  H    1  0   H  ...   
3    E0  11/08/2018        Wolves        Everton  2  2  D    1  1   D  ...   
4    E0  12/08/2018       Arsenal       Man City  0  2  A    0  1   A  ...   
..   ..         ...           ...            ... .. .. ..  ... ..  ..  ...   
372  E0  12/05/2019     Liverpool         Wolves  2  0  H    1  0   H  ...   
373  E0  12/05/2019    Man United        Cardiff  0  2  A    0  1   A  ...   
374  E0  12/05/2019   Southampton   Huddersfield  1  1  D    1  0   H  ...   
375  E0  12/05/2019     Tottenham        Everton  2  2  D    1  0   H  ...   
376  E0  12/05/2019       Watford       West Ham  1  4  A    0  2   A  ...   

     1.87  22  -0.25  2.18  2.11  1.81  1.77  2.62  3.38   2.9 

In [171]:
#change the index or make any of the column as index
#command is , index_col='Date'
df=pd.read_csv('season-1819_csv.csv',index_col='Date')
df

Div      HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR  \
Date                                                                           
10/08/2018  E0    Man United       Leicester     2     1   H     1     0   H   
11/08/2018  E0   Bournemouth         Cardiff     2     0   H     1     0   H   
11/08/2018  E0        Fulham  Crystal Palace     0     2   A     0     1   A   
11/08/2018  E0  Huddersfield         Chelsea     0     3   A     0     2   A   
11/08/2018  E0     Newcastle       Tottenham     1     2   A     1     2   A   
...         ..           ...             ...   ...   ...  ..   ...   ...  ..   
12/05/2019  E0     Liverpool          Wolves     2     0   H     1     0   H   
12/05/2019  E0    Man United         Cardiff     0     2   A     0     1   A   
12/05/2019  E0   Southampton    Huddersfield     1     1   D     1     0   H   
12/05/2019  E0     Tottenham         Everton     2     2   D     1     0   H   
12/05/2019  E0       Watford        West Ham     1     4   A     0     2   A   

               Referee  ...  BbAv<2.5  BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  \
Date                    ...                                                     
10/08/2018  A Marriner  ...      1.79    17  -0.75     1.75     1.70     2.29   
11/08/2018    K Friend  ...      1.83    20  -0.75     2.20     2.13     1.80   
11/08/2018      M Dean  ...      1.87    22  -0.25     2.18     2.11     1.81   
11/08/2018  C Kavanagh  ...      1.84    23   1.00     1.84     1.80     2.13   
11/08/2018  M Atkinson  ...      1.81    20   0.25     2.20     2.12     1.80   
...                ...  ...       ...   ...    ...      ...      ...      ...   
12/05/2019  M Atkinson  ...      2.31    22  -1.50     1.98     1.91     2.01   
12/05/2019      J Moss  ...      2.95    21  -2.00     2.52     2.32     1.72   
12/05/2019   L Probert  ...      2.29    22  -1.50     2.27     2.16     1.80   
12/05/2019  A Marriner  ...      2.07    19  -0.50     2.13     2.08     1.85   
12/05/2019  C Kavanagh  ...      2.44    19  -0.50     2.25     2.19     1.78   

            BbAvAHA  PSCH  PSCD  PSCA  
Date                                   
10/08/2018     2.21  1.55  4.07  7.69  
11/08/2018     1.75  1.88  3.61  4.70  
11/08/2018     1.77  2.62  3.38  2.90  
11/08/2018     2.06  7.24  3.95  1.58  
11/08/2018     1.76  4.74  3.53  1.89  
...             ...   ...   ...   ...  
12/05/2019     1.95  1.32  5.89  9.48  
12/05/2019     1.64  1.30  6.06  9.71  
12/05/2019     1.73  1.37  5.36  8.49  
12/05/2019     1.80  1.91  3.81  4.15  
12/05/2019     1.72  2.11  3.86  3.41  

[380 rows x 61 columns]

In [172]:
# Going to work with new file
#header, prefix, names

In [173]:
df=pd.read_csv('Fortune_10.csv')
df

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation               Health       2012  $10,597,009    
3   4         Mattouch          IT Services       2013  $14,026,934    
4   5        Techdrill               Health       2009  $10,573,990    
5   6         Techline               Health       2006  $13,898,119    
6   7          Cityace               Health       2010   $9,254,614    
7   8   Kayelectronics               Health       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [188]:
# to add the header or index just above the ID
df=pd.read_csv('Fortune_10.csv',header=0)
df

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation               Health       2012  $10,597,009    
3   4         Mattouch          IT Services       2013  $14,026,934    
4   5        Techdrill               Health       2009  $10,573,990    
5   6         Techline               Health       2006  $13,898,119    
6   7          Cityace               Health       2010   $9,254,614    
7   8   Kayelectronics               Health       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [189]:
df=pd.read_csv('Fortune_10.csv',header=None)
df

0                1                    2          3             4  \
0   ID             Name             Industry  Inception       Revenue   
1    1          Lamtone          IT Services       2009  $11,757,018    
2    2        Stripfind   Financial Services       2010  $12,329,371    
3    3  Canecorporation               Health       2012  $10,597,009    
4    4         Mattouch          IT Services       2013  $14,026,934    
5    5        Techdrill               Health       2009  $10,573,990    
6    6         Techline               Health       2006  $13,898,119    
7    7          Cityace               Health       2010   $9,254,614    
8    8   Kayelectronics               Health       2009   $9,451,943    
9    9          Ganzlax          IT Services       2011  $14,001,180    
10  10      Trantraxlax  Government Services       2011  $11,088,336    

                    5         6       7  
0            Expenses    Profit  Growth  
1   6,482,465 Dollars   5274553     30%  
2     916,455 Dollars  11412916     20%  
3   7,591,189 Dollars   3005820      7%  
4   7,429,377 Dollars   6597557     26%  
5   7,435,363 Dollars   3138627      8%  
6   5,470,303 Dollars   8427816     23%  
7   6,249,498 Dollars   3005116      6%  
8   3,878,113 Dollars   5573830      4%  
9                 NaN  11901180     18%  
10  5,635,276 Dollars   5453060      7%

In [190]:
df=pd.read_csv('Fortune_10.csv',header=None,prefix='columns')
df

columns0         columns1             columns2   columns3      columns4  \
0        ID             Name             Industry  Inception       Revenue   
1         1          Lamtone          IT Services       2009  $11,757,018    
2         2        Stripfind   Financial Services       2010  $12,329,371    
3         3  Canecorporation               Health       2012  $10,597,009    
4         4         Mattouch          IT Services       2013  $14,026,934    
5         5        Techdrill               Health       2009  $10,573,990    
6         6         Techline               Health       2006  $13,898,119    
7         7          Cityace               Health       2010   $9,254,614    
8         8   Kayelectronics               Health       2009   $9,451,943    
9         9          Ganzlax          IT Services       2011  $14,001,180    
10       10      Trantraxlax  Government Services       2011  $11,088,336    

             columns5  columns6 columns7  
0            Expenses    Profit   Growth  
1   6,482,465 Dollars   5274553      30%  
2     916,455 Dollars  11412916      20%  
3   7,591,189 Dollars   3005820       7%  
4   7,429,377 Dollars   6597557      26%  
5   7,435,363 Dollars   3138627       8%  
6   5,470,303 Dollars   8427816      23%  
7   6,249,498 Dollars   3005116       6%  
8   3,878,113 Dollars   5573830       4%  
9                 NaN  11901180      18%  
10  5,635,276 Dollars   5453060       7%

In [191]:
df=pd.read_csv('Fortune_10.csv',names=['a','b','c','d','e','f'])
df

a          b             c  \
ID Name                        Industry  Inception       Revenue   
1  Lamtone                  IT Services       2009  $11,757,018    
2  Stripfind         Financial Services       2010  $12,329,371    
3  Canecorporation               Health       2012  $10,597,009    
4  Mattouch                 IT Services       2013  $14,026,934    
5  Techdrill                     Health       2009  $10,573,990    
6  Techline                      Health       2006  $13,898,119    
7  Cityace                       Health       2010   $9,254,614    
8  Kayelectronics                Health       2009   $9,451,943    
9  Ganzlax                  IT Services       2011  $14,001,180    
10 Trantraxlax      Government Services       2011  $11,088,336    

                                    d         e       f  
ID Name                      Expenses    Profit  Growth  
1  Lamtone          6,482,465 Dollars   5274553     30%  
2  Stripfind          916,455 Dollars  11412916     20%  
3  Canecorporation  7,591,189 Dollars   3005820      7%  
4  Mattouch         7,429,377 Dollars   6597557     26%  
5  Techdrill        7,435,363 Dollars   3138627      8%  
6  Techline         5,470,303 Dollars   8427816     23%  
7  Cityace          6,249,498 Dollars   3005116      6%  
8  Kayelectronics   3,878,113 Dollars   5573830      4%  
9  Ganzlax                        NaN  11901180     18%  
10 Trantraxlax      5,635,276 Dollars   5453060      7%

In [192]:
df=pd.read_csv('Fortune_10.csv')
df.head()

ID             Name            Industry  Inception       Revenue  \
0   1          Lamtone         IT Services       2009  $11,757,018    
1   2        Stripfind  Financial Services       2010  $12,329,371    
2   3  Canecorporation              Health       2012  $10,597,009    
3   4         Mattouch         IT Services       2013  $14,026,934    
4   5        Techdrill              Health       2009  $10,573,990    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%

In [194]:
df=pd.read_csv('Fortune_12.csv',true_values=['Yes'],false_values=['No'])
df # change date into true and false

ID   Date             Name             Industry  Inception       Revenue  \
0   1   True          Lamtone          IT Services       2009  $11,757,018    
1   2  False        Stripfind   Financial Services       2010  $12,329,371    
2   3   True  Canecorporation               Health       2012  $10,597,009    
3   4  False         Mattouch          IT Services       2013  $14,026,934    
4   5   True        Techdrill               Health       2009  $10,573,990    
5   6  False         Techline               Health       2006  $13,898,119    
6   7   True          Cityace               Health       2010   $9,254,614    
7   8   True   Kayelectronics               Health       2009   $9,451,943    
8   9   True          Ganzlax          IT Services       2011  $14,001,180    
9  10   True      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [195]:
# Finding a missing value in pandas
#in pandas, Nan means the missing values...Not a number
#pandas consider following values as NaN
# N/A, #NA -1.#IND, -1.#QNAN -NaN,N/A,NA
#NULL,null, n/a, nan etc that means if you give these inputs in the csv file you will get the NaN as output

In [196]:
df=pd.read_csv('Fortune_15.csv')
df

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation                  NaN       2012  $10,597,009    
3   4         Mattouch                  NaN       2013  $14,026,934    
4   5        Techdrill        not available       2009  $10,573,990    
5   6         Techline                  NaN       2006  $13,898,119    
6   7          Cityace                  NaN       2010   $9,254,614    
7   8   Kayelectronics               Health       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit         Growth  
0  6,482,465 Dollars   5274553  not available  
1    916,455 Dollars  11412916  not available  
2  7,591,189 Dollars   3005820            NaN  
3  7,429,377 Dollars   6597557            NaN  
4  7,435,363 Dollars   3138627             8%  
5  5,470,303 Dollars   8427816            23%  
6  6,249,498 Dollars   3005116             6%  
7  3,878,113 Dollars   5573830             4%  
8                NaN  11901180            18%  
9  5,635,276 Dollars   5453060             7%

In [197]:
# Now to change not available to NaN
df=pd.read_csv('Fortune_15.csv',na_values='not available')
df

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation                  NaN       2012  $10,597,009    
3   4         Mattouch                  NaN       2013  $14,026,934    
4   5        Techdrill                  NaN       2009  $10,573,990    
5   6         Techline                  NaN       2006  $13,898,119    
6   7          Cityace                  NaN       2010   $9,254,614    
7   8   Kayelectronics               Health       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    NaN  
1    916,455 Dollars  11412916    NaN  
2  7,591,189 Dollars   3005820    NaN  
3  7,429,377 Dollars   6597557    NaN  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

# Pandas replace function syntax: DataFrame.replace

In [199]:
import pandas as pd
df=pd.read_csv('Fortune_10.csv')
df # file is in dataframe format

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation               Health       2012  $10,597,009    
3   4         Mattouch          IT Services       2013  $14,026,934    
4   5        Techdrill               Health       2009  $10,573,990    
5   6         Techline               Health       2006  $13,898,119    
6   7          Cityace               Health       2010   $9,254,614    
7   8   Kayelectronics               Health       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [200]:
df.replace(to_replace = 'Health',value='Finance')
# this changes Health to Finance

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation              Finance       2012  $10,597,009    
3   4         Mattouch          IT Services       2013  $14,026,934    
4   5        Techdrill              Finance       2009  $10,573,990    
5   6         Techline              Finance       2006  $13,898,119    
6   7          Cityace              Finance       2010   $9,254,614    
7   8   Kayelectronics              Finance       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [201]:
df.replace('Health','Finance') # the same thing

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation              Finance       2012  $10,597,009    
3   4         Mattouch          IT Services       2013  $14,026,934    
4   5        Techdrill              Finance       2009  $10,573,990    
5   6         Techline              Finance       2006  $13,898,119    
6   7          Cityace              Finance       2010   $9,254,614    
7   8   Kayelectronics              Finance       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [202]:
# Now apply for integer value for example 10 change to 50
df.replace(10,50)

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation               Health       2012  $10,597,009    
3   4         Mattouch          IT Services       2013  $14,026,934    
4   5        Techdrill               Health       2009  $10,573,990    
5   6         Techline               Health       2006  $13,898,119    
6   7          Cityace               Health       2010   $9,254,614    
7   8   Kayelectronics               Health       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  50      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [204]:
df.replace([1,2,3,4,5,6,7,8,9,10],0) # all of them will be changed into 0, look into ID.

ID             Name             Industry  Inception       Revenue  \
0   0          Lamtone          IT Services       2009  $11,757,018    
1   0        Stripfind   Financial Services       2010  $12,329,371    
2   0  Canecorporation               Health       2012  $10,597,009    
3   0         Mattouch          IT Services       2013  $14,026,934    
4   0        Techdrill               Health       2009  $10,573,990    
5   0         Techline               Health       2006  $13,898,119    
6   0          Cityace               Health       2010   $9,254,614    
7   0   Kayelectronics               Health       2009   $9,451,943    
8   0          Ganzlax          IT Services       2011  $14,001,180    
9   0      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [205]:
df.replace([1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20])

ID             Name             Industry  Inception       Revenue  \
0  11          Lamtone          IT Services       2009  $11,757,018    
1  12        Stripfind   Financial Services       2010  $12,329,371    
2  13  Canecorporation               Health       2012  $10,597,009    
3  14         Mattouch          IT Services       2013  $14,026,934    
4  15        Techdrill               Health       2009  $10,573,990    
5  16         Techline               Health       2006  $13,898,119    
6  17          Cityace               Health       2010   $9,254,614    
7  18   Kayelectronics               Health       2009   $9,451,943    
8  19          Ganzlax          IT Services       2011  $14,001,180    
9  20      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [207]:
# For particular column, if we need to change some values, then we use dictionary.
df.replace({'Industry':'Health'},'ODU')

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation                  ODU       2012  $10,597,009    
3   4         Mattouch          IT Services       2013  $14,026,934    
4   5        Techdrill                  ODU       2009  $10,573,990    
5   6         Techline                  ODU       2006  $13,898,119    
6   7          Cityace                  ODU       2010   $9,254,614    
7   8   Kayelectronics                  ODU       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

In [208]:
df.replace('[A-Za-z]',0)

ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018    
1   2        Stripfind   Financial Services       2010  $12,329,371    
2   3  Canecorporation               Health       2012  $10,597,009    
3   4         Mattouch          IT Services       2013  $14,026,934    
4   5        Techdrill               Health       2009  $10,573,990    
5   6         Techline               Health       2006  $13,898,119    
6   7          Cityace               Health       2010   $9,254,614    
7   8   Kayelectronics               Health       2009   $9,451,943    
8   9          Ganzlax          IT Services       2011  $14,001,180    
9  10      Trantraxlax  Government Services       2011  $11,088,336    

            Expenses    Profit Growth  
0  6,482,465 Dollars   5274553    30%  
1    916,455 Dollars  11412916    20%  
2  7,591,189 Dollars   3005820     7%  
3  7,429,377 Dollars   6597557    26%  
4  7,435,363 Dollars   3138627     8%  
5  5,470,303 Dollars   8427816    23%  
6  6,249,498 Dollars   3005116     6%  
7  3,878,113 Dollars   5573830     4%  
8                NaN  11901180    18%  
9  5,635,276 Dollars   5453060     7%

# Pandas loc method:syntax::DataFrame,loc[]

In [209]:
#group of rows and columns can be accessed  by their labels
#it basically returns the desired location value

In [210]:
import pandas as pd
df=pd.read_csv('student_results.csv')
df

Student ID  Class  Study hrs  Sleeping hrs  Social Media usage hrs  \
0        1001     10          2             9                       3   
1        1002     10          6             8                       2   
2        1003     10          3             8                       2   
3        1004     11          0            10                       1   
4        1005     11          4             7                       2   
5        1006     11         10             7                       0   
6        1007     12          4             6                       0   
7        1008     12         10             6                       2   
8        1009     12          2             8                       2   
9        1010     12          6             9                       1   

   Mobile Games hrs  Percantege  
0                 5          50  
1                 0          80  
2                 4          60  
3                 5          45  
4                 0          75  
5                 0          96  
6                 0          80  
7                 0          90  
8                 4          60  
9                 0          85

In [212]:
df.loc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [213]:
df.loc[9]

Student ID                1010
Class                       12
Study hrs                    6
Sleeping hrs                 9
Social Media usage hrs       1
Mobile Games hrs             0
Percantege                  85
Name: 9, dtype: int64

In [214]:
df.loc[[0,1]]

Student ID  Class  Study hrs  Sleeping hrs  Social Media usage hrs  \
0        1001     10          2             9                       3   
1        1002     10          6             8                       2   

   Mobile Games hrs  Percantege  
0                 5          50  
1                 0          80

In [215]:
df.loc[[2,4]]

Student ID  Class  Study hrs  Sleeping hrs  Social Media usage hrs  \
2        1003     10          3             8                       2   
4        1005     11          4             7                       2   

   Mobile Games hrs  Percantege  
2                 4          60  
4                 0          75

In [216]:
df.loc[4,'Class']

11

In [221]:
df.loc[0:3,'Class']

0    10
1    10
2    10
3    11
Name: Class, dtype: int64

# There are other methods to deal with datas in pandas. Great!

In [222]:
# Thanks Bishnu Ji.